# Faster builds without sudo.
sudo: false
dist: trusty
language: java
notifications:
  email: false
cache:
  directories:
  - "$HOME/.cache"
script: mvn
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/Jobs4.13.1.jar"
  on:
    tags: true
